### ISSUE TITLE
not displaying search results beyond 10.000

### ISSUE THREAD

**Issue by germakoci** [liquidinvestigations/hoover-search#35]
When searching a term that has more then 10.000 hits (e.g. "done"), Hoover will display only up to 10.000 results (no matter if I choose 10 or 1.000 results per page). 

When trying to go to the page that would display the messages from 10.001 onwards, an error message is displayed: "Unknown server error while searching". Is this a Hoover search limitation or a Hoover UI ?

The exact same problem I encounter with your UI application @jarib on https://hoover-ui.herokuapp.com/. The message reads "Error: unable to fetch https://hoover-ui.herokuapp.com/search: 500 Internal Server Error"

**Comment by ioanvpocol** [comment]
This is a ES setting, index.max_result_window that is 10 000 by default.

Temporary it can be set to a larger value with this request: 
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html

The best solution is to implement the pagination for large sets:
https://www.elastic.co/guide/en/elasticsearch/reference/5.4/search-request-search-after.html

**Comment by germakoci** [comment]
@ioanvpocol this needs to be done by @salevajo I guess ?

**Comment by jarib** [comment]
Pagination using `search_after` would require changes in `hoover/ui` and `hoover/search`. Once we're upgraded to an ES version that supports it, it should be a quite simple change to make.

**Comment by ioanvpocol** [comment]
The pagination with search_after is almost done, I will make the PR along with the other changes required for ES6.
